<?php

declare(strict_types=1);

namespace Makhnanov\TelegramBot\Type;

readonly class ChatFullInfo
{
    public function __construct(
        public int $id,
        public string $type,
        public int $accentColorId,
        public int $maxReactionCount,
        public AcceptedGiftTypes $acceptedGiftTypes,
        public ?string $title = null,
        public ?string $username = null,
        public ?string $firstName = null,
        public ?string $lastName = null,
        public ?bool $isForum = null,
        public ?bool $isDirectMessages = null,
        public ?ChatPhoto $photo = null,
        public ?array $activeUsernames = null,
        public ?Birthdate $birthdate = null,
        public ?BusinessIntro $businessIntro = null,
        public ?BusinessLocation $businessLocation = null,
        public ?BusinessOpeningHours $businessOpeningHours = null,
        public ?Chat $personalChat = null,
        public ?Chat $parentChat = null,
        public ?array $availableReactions = null,
        public ?string $backgroundCustomEmojiId = null,
        public ?int $profileAccentColorId = null,
        public ?string $profileBackgroundCustomEmojiId = null,
        public ?string $emojiStatusCustomEmojiId = null,
        public ?int $emojiStatusExpirationDate = null,
        public ?string $bio = null,
        public ?bool $hasPrivateForwards = null,
        public ?bool $hasRestrictedVoiceAndVideoMessages = null,
        public ?bool $joinToSendMessages = null,
        public ?bool $joinByRequest = null,
        public ?string $description = null,
        public ?string $inviteLink = null,
        public ?Message $pinnedMessage = null,
        public ?ChatPermissions $permissions = null,
        public ?bool $canSendPaidMedia = null,
        public ?int $slowModeDelay = null,
        public ?int $unrestrictBoostCount = null,
        public ?int $messageAutoDeleteTime = null,
        public ?bool $hasAggressiveAntiSpamEnabled = null,
        public ?bool $hasHiddenMembers = null,
        public ?bool $hasProtectedContent = null,
        public ?bool $hasVisibleHistory = null,
        public ?string $stickerSetName = null,
        public ?bool $canSetStickerSet = null,
        public ?string $customEmojiStickerSetName = null,
        public ?int $linkedChatId = null,
        public ?ChatLocation $location = null,
        public ?UserRating $rating = null,
        public ?UniqueGiftColors $uniqueGiftColors = null,
        public ?int $paidMessageStarCount = null,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            type: $data['type'],
            title: $data['title'] ?? null,
            username: $data['username'] ?? null,
            firstName: $data['first_name'] ?? null,
            lastName: $data['last_name'] ?? null,
            isForum: $data['is_forum'] ?? null,
            isDirectMessages: $data['is_direct_messages'] ?? null,
            accentColorId: $data['accent_color_id'],
            maxReactionCount: $data['max_reaction_count'],
            photo: isset($data['photo']) ? ChatPhoto::fromArray($data['photo']) : null,
            activeUsernames: $data['active_usernames'] ?? null,
            birthdate: isset($data['birthdate']) ? Birthdate::fromArray($data['birthdate']) : null,
            businessIntro: isset($data['business_intro']) ? BusinessIntro::fromArray($data['business_intro']) : null,
            businessLocation: isset($data['business_location']) ? BusinessLocation::fromArray($data['business_location']) : null,
            businessOpeningHours: isset($data['business_opening_hours']) ? BusinessOpeningHours::fromArray($data['business_opening_hours']) : null,
            personalChat: isset($data['personal_chat']) ? Chat::fromArray($data['personal_chat']) : null,
            parentChat: isset($data['parent_chat']) ? Chat::fromArray($data['parent_chat']) : null,
            availableReactions: isset($data['available_reactions']) ? array_map(ReactionType::fromArray(...), $data['available_reactions']) : null,
            backgroundCustomEmojiId: $data['background_custom_emoji_id'] ?? null,
            profileAccentColorId: $data['profile_accent_color_id'] ?? null,
            profileBackgroundCustomEmojiId: $data['profile_background_custom_emoji_id'] ?? null,
            emojiStatusCustomEmojiId: $data['emoji_status_custom_emoji_id'] ?? null,
            emojiStatusExpirationDate: $data['emoji_status_expiration_date'] ?? null,
            bio: $data['bio'] ?? null,
            hasPrivateForwards: $data['has_private_forwards'] ?? null,
            hasRestrictedVoiceAndVideoMessages: $data['has_restricted_voice_and_video_messages'] ?? null,
            joinToSendMessages: $data['join_to_send_messages'] ?? null,
            joinByRequest: $data['join_by_request'] ?? null,
            description: $data['description'] ?? null,
            inviteLink: $data['invite_link'] ?? null,
            pinnedMessage: isset($data['pinned_message']) ? Message::fromArray($data['pinned_message']) : null,
            permissions: isset($data['permissions']) ? ChatPermissions::fromArray($data['permissions']) : null,
            acceptedGiftTypes: AcceptedGiftTypes::fromArray($data['accepted_gift_types']),
            canSendPaidMedia: $data['can_send_paid_media'] ?? null,
            slowModeDelay: $data['slow_mode_delay'] ?? null,
            unrestrictBoostCount: $data['unrestrict_boost_count'] ?? null,
            messageAutoDeleteTime: $data['message_auto_delete_time'] ?? null,
            hasAggressiveAntiSpamEnabled: $data['has_aggressive_anti_spam_enabled'] ?? null,
            hasHiddenMembers: $data['has_hidden_members'] ?? null,
            hasProtectedContent: $data['has_protected_content'] ?? null,
            hasVisibleHistory: $data['has_visible_history'] ?? null,
            stickerSetName: $data['sticker_set_name'] ?? null,
            canSetStickerSet: $data['can_set_sticker_set'] ?? null,
            customEmojiStickerSetName: $data['custom_emoji_sticker_set_name'] ?? null,
            linkedChatId: $data['linked_chat_id'] ?? null,
            location: isset($data['location']) ? ChatLocation::fromArray($data['location']) : null,
            rating: isset($data['rating']) ? UserRating::fromArray($data['rating']) : null,
            uniqueGiftColors: isset($data['unique_gift_colors']) ? UniqueGiftColors::fromArray($data['unique_gift_colors']) : null,
            paidMessageStarCount: $data['paid_message_star_count'] ?? null,
        );
    }
}
