<?php

declare(strict_types=1);

namespace Makhnanov\TelegramBot\Type;

readonly class Message
{
    public function __construct(
        public int $messageId,
        public int $date,
        public Chat $chat,
        public ?int $messageThreadId = null,
        public ?DirectMessagesTopic $directMessagesTopic = null,
        public ?User $from = null,
        public ?Chat $senderChat = null,
        public ?int $senderBoostCount = null,
        public ?User $senderBusinessBot = null,
        public ?string $businessConnectionId = null,
        public ?MessageOrigin $forwardOrigin = null,
        public ?bool $isTopicMessage = null,
        public ?bool $isAutomaticForward = null,
        public ?Message $replyToMessage = null,
        public ?ExternalReplyInfo $externalReply = null,
        public ?TextQuote $quote = null,
        public ?Story $replyToStory = null,
        public ?int $replyToChecklistTaskId = null,
        public ?User $viaBot = null,
        public ?int $editDate = null,
        public ?bool $hasProtectedContent = null,
        public ?bool $isFromOffline = null,
        public ?bool $isPaidPost = null,
        public ?string $mediaGroupId = null,
        public ?string $authorSignature = null,
        public ?int $paidStarCount = null,
        public ?string $text = null,
        public ?array $entities = null,
        public ?LinkPreviewOptions $linkPreviewOptions = null,
        public ?SuggestedPostInfo $suggestedPostInfo = null,
        public ?string $effectId = null,
        public ?Animation $animation = null,
        public ?Audio $audio = null,
        public ?Document $document = null,
        public ?PaidMediaInfo $paidMedia = null,
        public ?array $photo = null,
        public ?Sticker $sticker = null,
        public ?Story $story = null,
        public ?Video $video = null,
        public ?VideoNote $videoNote = null,
        public ?Voice $voice = null,
        public ?string $caption = null,
        public ?array $captionEntities = null,
        public ?bool $showCaptionAboveMedia = null,
        public ?bool $hasMediaSpoiler = null,
        public ?Checklist $checklist = null,
        public ?Contact $contact = null,
        public ?Dice $dice = null,
        public ?Game $game = null,
        public ?Poll $poll = null,
        public ?Venue $venue = null,
        public ?Location $location = null,
        public ?array $newChatMembers = null,
        public ?User $leftChatMember = null,
        public ?string $newChatTitle = null,
        public ?array $newChatPhoto = null,
        public ?bool $deleteChatPhoto = null,
        public ?bool $groupChatCreated = null,
        public ?bool $supergroupChatCreated = null,
        public ?bool $channelChatCreated = null,
        public ?MessageAutoDeleteTimerChanged $messageAutoDeleteTimerChanged = null,
        public ?int $migrateToChatId = null,
        public ?int $migrateFromChatId = null,
        public ?MaybeInaccessibleMessage $pinnedMessage = null,
        public ?Invoice $invoice = null,
        public ?SuccessfulPayment $successfulPayment = null,
        public ?RefundedPayment $refundedPayment = null,
        public ?UsersShared $usersShared = null,
        public ?ChatShared $chatShared = null,
        public ?GiftInfo $gift = null,
        public ?UniqueGiftInfo $uniqueGift = null,
        public ?GiftInfo $giftUpgradeSent = null,
        public ?string $connectedWebsite = null,
        public ?WriteAccessAllowed $writeAccessAllowed = null,
        public ?PassportData $passportData = null,
        public ?ProximityAlertTriggered $proximityAlertTriggered = null,
        public ?ChatBoostAdded $boostAdded = null,
        public ?ChatBackground $chatBackgroundSet = null,
        public ?ChecklistTasksDone $checklistTasksDone = null,
        public ?ChecklistTasksAdded $checklistTasksAdded = null,
        public ?DirectMessagePriceChanged $directMessagePriceChanged = null,
        public ?ForumTopicCreated $forumTopicCreated = null,
        public ?ForumTopicEdited $forumTopicEdited = null,
        public ?ForumTopicClosed $forumTopicClosed = null,
        public ?ForumTopicReopened $forumTopicReopened = null,
        public ?GeneralForumTopicHidden $generalForumTopicHidden = null,
        public ?GeneralForumTopicUnhidden $generalForumTopicUnhidden = null,
        public ?GiveawayCreated $giveawayCreated = null,
        public ?Giveaway $giveaway = null,
        public ?GiveawayWinners $giveawayWinners = null,
        public ?GiveawayCompleted $giveawayCompleted = null,
        public ?PaidMessagePriceChanged $paidMessagePriceChanged = null,
        public ?SuggestedPostApproved $suggestedPostApproved = null,
        public ?SuggestedPostApprovalFailed $suggestedPostApprovalFailed = null,
        public ?SuggestedPostDeclined $suggestedPostDeclined = null,
        public ?SuggestedPostPaid $suggestedPostPaid = null,
        public ?SuggestedPostRefunded $suggestedPostRefunded = null,
        public ?VideoChatScheduled $videoChatScheduled = null,
        public ?VideoChatStarted $videoChatStarted = null,
        public ?VideoChatEnded $videoChatEnded = null,
        public ?VideoChatParticipantsInvited $videoChatParticipantsInvited = null,
        public ?WebAppData $webAppData = null,
        public ?InlineKeyboardMarkup $replyMarkup = null,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            messageId: $data['message_id'],
            messageThreadId: $data['message_thread_id'] ?? null,
            directMessagesTopic: isset($data['direct_messages_topic']) ? DirectMessagesTopic::fromArray($data['direct_messages_topic']) : null,
            from: isset($data['from']) ? User::fromArray($data['from']) : null,
            senderChat: isset($data['sender_chat']) ? Chat::fromArray($data['sender_chat']) : null,
            senderBoostCount: $data['sender_boost_count'] ?? null,
            senderBusinessBot: isset($data['sender_business_bot']) ? User::fromArray($data['sender_business_bot']) : null,
            date: $data['date'],
            businessConnectionId: $data['business_connection_id'] ?? null,
            chat: Chat::fromArray($data['chat']),
            forwardOrigin: isset($data['forward_origin']) ? MessageOrigin::fromArray($data['forward_origin']) : null,
            isTopicMessage: $data['is_topic_message'] ?? null,
            isAutomaticForward: $data['is_automatic_forward'] ?? null,
            replyToMessage: isset($data['reply_to_message']) ? Message::fromArray($data['reply_to_message']) : null,
            externalReply: isset($data['external_reply']) ? ExternalReplyInfo::fromArray($data['external_reply']) : null,
            quote: isset($data['quote']) ? TextQuote::fromArray($data['quote']) : null,
            replyToStory: isset($data['reply_to_story']) ? Story::fromArray($data['reply_to_story']) : null,
            replyToChecklistTaskId: $data['reply_to_checklist_task_id'] ?? null,
            viaBot: isset($data['via_bot']) ? User::fromArray($data['via_bot']) : null,
            editDate: $data['edit_date'] ?? null,
            hasProtectedContent: $data['has_protected_content'] ?? null,
            isFromOffline: $data['is_from_offline'] ?? null,
            isPaidPost: $data['is_paid_post'] ?? null,
            mediaGroupId: $data['media_group_id'] ?? null,
            authorSignature: $data['author_signature'] ?? null,
            paidStarCount: $data['paid_star_count'] ?? null,
            text: $data['text'] ?? null,
            entities: isset($data['entities']) ? array_map(MessageEntity::fromArray(...), $data['entities']) : null,
            linkPreviewOptions: isset($data['link_preview_options']) ? LinkPreviewOptions::fromArray($data['link_preview_options']) : null,
            suggestedPostInfo: isset($data['suggested_post_info']) ? SuggestedPostInfo::fromArray($data['suggested_post_info']) : null,
            effectId: $data['effect_id'] ?? null,
            animation: isset($data['animation']) ? Animation::fromArray($data['animation']) : null,
            audio: isset($data['audio']) ? Audio::fromArray($data['audio']) : null,
            document: isset($data['document']) ? Document::fromArray($data['document']) : null,
            paidMedia: isset($data['paid_media']) ? PaidMediaInfo::fromArray($data['paid_media']) : null,
            photo: isset($data['photo']) ? array_map(PhotoSize::fromArray(...), $data['photo']) : null,
            sticker: isset($data['sticker']) ? Sticker::fromArray($data['sticker']) : null,
            story: isset($data['story']) ? Story::fromArray($data['story']) : null,
            video: isset($data['video']) ? Video::fromArray($data['video']) : null,
            videoNote: isset($data['video_note']) ? VideoNote::fromArray($data['video_note']) : null,
            voice: isset($data['voice']) ? Voice::fromArray($data['voice']) : null,
            caption: $data['caption'] ?? null,
            captionEntities: isset($data['caption_entities']) ? array_map(MessageEntity::fromArray(...), $data['caption_entities']) : null,
            showCaptionAboveMedia: $data['show_caption_above_media'] ?? null,
            hasMediaSpoiler: $data['has_media_spoiler'] ?? null,
            checklist: isset($data['checklist']) ? Checklist::fromArray($data['checklist']) : null,
            contact: isset($data['contact']) ? Contact::fromArray($data['contact']) : null,
            dice: isset($data['dice']) ? Dice::fromArray($data['dice']) : null,
            game: isset($data['game']) ? Game::fromArray($data['game']) : null,
            poll: isset($data['poll']) ? Poll::fromArray($data['poll']) : null,
            venue: isset($data['venue']) ? Venue::fromArray($data['venue']) : null,
            location: isset($data['location']) ? Location::fromArray($data['location']) : null,
            newChatMembers: isset($data['new_chat_members']) ? array_map(User::fromArray(...), $data['new_chat_members']) : null,
            leftChatMember: isset($data['left_chat_member']) ? User::fromArray($data['left_chat_member']) : null,
            newChatTitle: $data['new_chat_title'] ?? null,
            newChatPhoto: isset($data['new_chat_photo']) ? array_map(PhotoSize::fromArray(...), $data['new_chat_photo']) : null,
            deleteChatPhoto: $data['delete_chat_photo'] ?? null,
            groupChatCreated: $data['group_chat_created'] ?? null,
            supergroupChatCreated: $data['supergroup_chat_created'] ?? null,
            channelChatCreated: $data['channel_chat_created'] ?? null,
            messageAutoDeleteTimerChanged: isset($data['message_auto_delete_timer_changed']) ? MessageAutoDeleteTimerChanged::fromArray($data['message_auto_delete_timer_changed']) : null,
            migrateToChatId: $data['migrate_to_chat_id'] ?? null,
            migrateFromChatId: $data['migrate_from_chat_id'] ?? null,
            pinnedMessage: isset($data['pinned_message']) ? MaybeInaccessibleMessage::fromArray($data['pinned_message']) : null,
            invoice: isset($data['invoice']) ? Invoice::fromArray($data['invoice']) : null,
            successfulPayment: isset($data['successful_payment']) ? SuccessfulPayment::fromArray($data['successful_payment']) : null,
            refundedPayment: isset($data['refunded_payment']) ? RefundedPayment::fromArray($data['refunded_payment']) : null,
            usersShared: isset($data['users_shared']) ? UsersShared::fromArray($data['users_shared']) : null,
            chatShared: isset($data['chat_shared']) ? ChatShared::fromArray($data['chat_shared']) : null,
            gift: isset($data['gift']) ? GiftInfo::fromArray($data['gift']) : null,
            uniqueGift: isset($data['unique_gift']) ? UniqueGiftInfo::fromArray($data['unique_gift']) : null,
            giftUpgradeSent: isset($data['gift_upgrade_sent']) ? GiftInfo::fromArray($data['gift_upgrade_sent']) : null,
            connectedWebsite: $data['connected_website'] ?? null,
            writeAccessAllowed: isset($data['write_access_allowed']) ? WriteAccessAllowed::fromArray($data['write_access_allowed']) : null,
            passportData: isset($data['passport_data']) ? PassportData::fromArray($data['passport_data']) : null,
            proximityAlertTriggered: isset($data['proximity_alert_triggered']) ? ProximityAlertTriggered::fromArray($data['proximity_alert_triggered']) : null,
            boostAdded: isset($data['boost_added']) ? ChatBoostAdded::fromArray($data['boost_added']) : null,
            chatBackgroundSet: isset($data['chat_background_set']) ? ChatBackground::fromArray($data['chat_background_set']) : null,
            checklistTasksDone: isset($data['checklist_tasks_done']) ? ChecklistTasksDone::fromArray($data['checklist_tasks_done']) : null,
            checklistTasksAdded: isset($data['checklist_tasks_added']) ? ChecklistTasksAdded::fromArray($data['checklist_tasks_added']) : null,
            directMessagePriceChanged: isset($data['direct_message_price_changed']) ? DirectMessagePriceChanged::fromArray($data['direct_message_price_changed']) : null,
            forumTopicCreated: isset($data['forum_topic_created']) ? ForumTopicCreated::fromArray($data['forum_topic_created']) : null,
            forumTopicEdited: isset($data['forum_topic_edited']) ? ForumTopicEdited::fromArray($data['forum_topic_edited']) : null,
            forumTopicClosed: isset($data['forum_topic_closed']) ? ForumTopicClosed::fromArray($data['forum_topic_closed']) : null,
            forumTopicReopened: isset($data['forum_topic_reopened']) ? ForumTopicReopened::fromArray($data['forum_topic_reopened']) : null,
            generalForumTopicHidden: isset($data['general_forum_topic_hidden']) ? GeneralForumTopicHidden::fromArray($data['general_forum_topic_hidden']) : null,
            generalForumTopicUnhidden: isset($data['general_forum_topic_unhidden']) ? GeneralForumTopicUnhidden::fromArray($data['general_forum_topic_unhidden']) : null,
            giveawayCreated: isset($data['giveaway_created']) ? GiveawayCreated::fromArray($data['giveaway_created']) : null,
            giveaway: isset($data['giveaway']) ? Giveaway::fromArray($data['giveaway']) : null,
            giveawayWinners: isset($data['giveaway_winners']) ? GiveawayWinners::fromArray($data['giveaway_winners']) : null,
            giveawayCompleted: isset($data['giveaway_completed']) ? GiveawayCompleted::fromArray($data['giveaway_completed']) : null,
            paidMessagePriceChanged: isset($data['paid_message_price_changed']) ? PaidMessagePriceChanged::fromArray($data['paid_message_price_changed']) : null,
            suggestedPostApproved: isset($data['suggested_post_approved']) ? SuggestedPostApproved::fromArray($data['suggested_post_approved']) : null,
            suggestedPostApprovalFailed: isset($data['suggested_post_approval_failed']) ? SuggestedPostApprovalFailed::fromArray($data['suggested_post_approval_failed']) : null,
            suggestedPostDeclined: isset($data['suggested_post_declined']) ? SuggestedPostDeclined::fromArray($data['suggested_post_declined']) : null,
            suggestedPostPaid: isset($data['suggested_post_paid']) ? SuggestedPostPaid::fromArray($data['suggested_post_paid']) : null,
            suggestedPostRefunded: isset($data['suggested_post_refunded']) ? SuggestedPostRefunded::fromArray($data['suggested_post_refunded']) : null,
            videoChatScheduled: isset($data['video_chat_scheduled']) ? VideoChatScheduled::fromArray($data['video_chat_scheduled']) : null,
            videoChatStarted: isset($data['video_chat_started']) ? VideoChatStarted::fromArray($data['video_chat_started']) : null,
            videoChatEnded: isset($data['video_chat_ended']) ? VideoChatEnded::fromArray($data['video_chat_ended']) : null,
            videoChatParticipantsInvited: isset($data['video_chat_participants_invited']) ? VideoChatParticipantsInvited::fromArray($data['video_chat_participants_invited']) : null,
            webAppData: isset($data['web_app_data']) ? WebAppData::fromArray($data['web_app_data']) : null,
            replyMarkup: isset($data['reply_markup']) ? InlineKeyboardMarkup::fromArray($data['reply_markup']) : null,
        );
    }
}
